[package]
name = "hyper-echo-server"
version = "0.1.0"
edition = "2021"

[dependencies]
http-body-util = "0.1.1"
hyper = { version = "1.3.1", features = ["full"] }
hyper-util = { version = "0.1.3", features = ["full"] }
json = "0.12.4"
tokio = { version = "1.37.0", features = ["full"] }
